---
namespace: community
name: sonic
version: 0.2.0
readme: README.md
authors:
  - Christian Svensson (@bluecmd)
description: Ansible collection for the open-source SONiC Network Operating System
license_file: LICENSE
tags:
  - sonic
  - nos
  - networking
repository: https://github.com/ansible-collections/community.sonic
homepage: https://github.com/ansible-collections/community.sonic
issues: https://github.com/ansible-collections/community.sonic/issues
build_ignore:
  - .gitignore
  - changelogs/.plugin-cache.yaml
  - testbed
  - tests
